Added tls configuration flags for CAPM3.
metal3-io/cluster-api-provider-metal3 pull request #1041
Opened 2023-06-14 10:09 UTC by as20203

Added tls configuration flags for CAPM3 repositories.

2023-06-14 10:10 UTC, as20203 commented
/hold

2023-06-14 10:42 UTC, tuminoid commented on main_test.go
> +Copyright 2023 The Kubernetes Authors.
Metal3 authors again.

Also the whole header looks to be formatted funny.

2023-06-16 05:50 UTC, tuminoid commented
Building manager and running `./bin/manager --help` says:

```
  -tls-max-version string
    	The maximum TLS version in use by the webhook server.
    	Possible values are VersionTLS10, VersionTLS11, VersionTLS12, VersionTLS13. (default "VersionTLS13")
  -tls-min-version string
    	The minimum TLS version in use by the webhook server.
    	Possible values are VersionTLS10, VersionTLS11, VersionTLS12, VersionTLS13. (default "VersionTLS12")
```

We are not supporting TLS 1.0 or TLS 1.1.

2023-06-21 11:55 UTC, as20203 commented
/test-centos-e2e-integration-main

2023-06-21 11:55 UTC, as20203 commented
/test-ubuntu-integration-main

2023-06-21 13:51 UTC, as20203 commented
/test-ubuntu-integration-main
/test-centos-e2e-integration-main

2023-06-22 07:04 UTC, tuminoid commented
/test-ubuntu-integration-main
/test-centos-e2e-integration-main

2023-06-22 10:51 UTC, tuminoid requested changes

2023-06-22 10:51 UTC, tuminoid commented on main.go
> +	flag.StringVar(&tlsOptions.TLSMinVersion, "tls-min-version", "VersionTLS12",
Default version is wrong, should be `TLS12`

2023-06-22 10:51 UTC, tuminoid commented on main.go
> +	fs.StringVar(&tlsOptions.TLSMaxVersion, "tls-max-version", "VersionTLS13",
Default version is wrong, should be `TLS13`

2023-06-22 11:00 UTC, tuminoid commented
/test-ubuntu-integration-main
/test-centos-e2e-integration-main

2023-06-26 05:27 UTC, tuminoid approved these changes
/lgtm

2023-06-26 07:00 UTC, tuminoid commented
/unhold
/assign @mboukhalfa @lentzi90

2023-06-26 07:15 UTC, lentzi90 reviewed
/approve

2023-06-26 07:16 UTC, merged