✨ Add test failing and flaking issue templates
metal3-io/cluster-api-provider-metal3 pull request #1081
Opened 2023-07-10 08:54 UTC by mboukhalfa

Adding templates to report CI failures

2023-07-10 09:27 UTC, mboukhalfa commented
/test-centos-e2e-integration-main
/test-ubuntu-integration-main

2023-07-10 11:18 UTC, mboukhalfa commented
/test-centos-e2e-integration-main

2023-07-10 15:47 UTC, mboukhalfa commented
/test-centos-e2e-integration-main

2023-07-10 16:54 UTC, mboukhalfa commented
/test-centos-e2e-integration-main

2023-07-11 01:32 UTC, zhouhao3 commented
/lgtm

2023-07-11 08:12 UTC, mboukhalfa commented
/assign @kashifest 
cc @furkatgofurov7

2023-07-11 09:01 UTC, furkatgofurov7 requested changes

2023-07-11 10:19 UTC, mboukhalfa commented on .github/ISSUE_TEMPLATE/flaking-test.yaml
> +labels: kind/flake
done

2023-07-11 10:20 UTC, mboukhalfa commented
/test-centos-e2e-integration-main
/test-ubuntu-integration-main

2023-07-11 12:45 UTC, mboukhalfa commented
/test-centos-e2e-integration-main

2023-07-11 12:46 UTC, mboukhalfa commented
> /lgtm

@zhouhao3 Can you re lgtm!

2023-07-11 13:10 UTC, furkatgofurov7 approved these changes

2023-07-11 15:37 UTC, smoshiur1237 commented
\lgtm

2023-07-11 15:38 UTC, merged