🌱 Bump CAPI to v1.6.1
metal3-io/cluster-api-provider-metal3 pull request #1406
Opened 2024-01-16 19:08 UTC by Sunnatillo

as title

2024-01-16 19:10 UTC, Sunnatillo commented
/test-centos-e2e-integration-main
/test-ubuntu-integration-main

2024-01-17 05:39 UTC, tuminoid reviewed
/lgtm

2024-01-17 05:40 UTC, tuminoid commented
Cherry-pick to 1.6 branch?

2024-01-17 07:26 UTC, kashifest requested changes

2024-01-17 07:26 UTC, kashifest commented on README.md
> +   clusterctl init --core cluster-api:v1.6.1 --bootstrap kubeadm:v1.6.0 \
```suggestion
   clusterctl init --core cluster-api:v1.6.1 --bootstrap kubeadm:v1.6.1 \
   --control-plane kubeadm:v1.6.1 -v5
```

2024-01-17 08:05 UTC, Sunnatillo commented on README.md
> +   clusterctl init --core cluster-api:v1.6.1 --bootstrap kubeadm:v1.6.0 \
done

2024-01-17 08:05 UTC, Sunnatillo commented
/test-centos-e2e-integration-main
/test-ubuntu-integration-main

2024-01-17 08:10 UTC, kashifest commented
/approve

2024-01-17 08:11 UTC, kashifest approved these changes

2024-01-17 08:11 UTC, tuminoid reviewed
/lgtm

/test-centos-e2e-integration-main
/test-ubuntu-integration-main

2024-01-17 09:08 UTC, merged

2024-01-17 09:26 UTC, Sunnatillo commented
/cherry-pick release-1.6