🌱 Bump CAPI to v1.5.5
metal3-io/cluster-api-provider-metal3 pull request #1407
Opened 2024-01-16 19:09 UTC by Sunnatillo

as title

2024-01-16 19:10 UTC, Sunnatillo commented
/test-ubuntu-e2e-integration-release-1-5

2024-01-17 05:40 UTC, tuminoid reviewed
/lgtm

2024-01-17 07:27 UTC, kashifest requested changes
one comment inline

2024-01-17 08:05 UTC, kashifest approved these changes
/approve

2024-01-17 08:06 UTC, Sunnatillo commented on README.md
> +   clusterctl init --core cluster-api:v1.5.5 --bootstrap kubeadm:v1.5.3 \
done

2024-01-17 08:06 UTC, Sunnatillo commented
/test-ubuntu-e2e-integration-release-1-5

2024-01-17 08:10 UTC, tuminoid reviewed
/lgtm

2024-01-17 09:26 UTC, Sunnatillo commented
/test-ubuntu-e2e-integration-release-1-5

2024-01-17 10:12 UTC, merged