🐛 e2e: Specify ip address pool for retreiving ip for ssh ing node
metal3-io/cluster-api-provider-metal3 pull request #1528
Opened 2024-03-15 13:59 UTC by Sunnatillo

2024-03-15 14:01 UTC, Sunnatillo commented
/test-ubuntu-e2e-feature-main

2024-03-15 15:11 UTC, Sunnatillo commented
/test-ubuntu-e2e-feature-main

2024-03-15 15:59 UTC, Sunnatillo commented
/test-centos-e2e-feature-main

2024-03-15 16:51 UTC, Sunnatillo commented
/test-ubuntu-e2e-feature-main

2024-03-18 07:00 UTC, kashifest requested changes

2024-03-18 08:43 UTC, Sunnatillo commented
/test-ubuntu-e2e-feature-main

2024-03-18 09:51 UTC, Sunnatillo commented
/test-ubuntu-e2e-feature-main

2024-03-18 09:52 UTC, Sunnatillo commented on test/e2e/common.go
> +		Namespace:   m.Spec.ClusterName,
Thanks

2024-03-18 12:01 UTC, Sunnatillo commented
networking issue

2024-03-18 12:02 UTC, Sunnatillo commented
/test-ubuntu-e2e-feature-main 
previous one failed with networking issue

2024-03-18 13:30 UTC, kashifest reviewed
/approve

2024-03-18 13:58 UTC, Sunnatillo commented
/test-ubuntu-integration-main 
/est-centos-e2e-integration-main

2024-03-18 15:16 UTC, Sunnatillo commented
Previous fail is not related to this change.
/test-ubuntu-e2e-feature-main

2024-03-18 20:43 UTC, Sunnatillo commented
/test-centos-e2e-integration-main 
/test-ubuntu-integration-main

2024-03-19 07:10 UTC, Sunnatillo commented
/test-centos-e2e-integration-main
/test-ubuntu-integration-main

2024-03-19 09:02 UTC, smoshiur1237 reviewed
/lgtm

2024-03-19 09:04 UTC, kashifest approved these changes

2024-03-19 09:06 UTC, merged

2024-03-19 11:00 UTC, Sunnatillo commented
/cherry-pick release-1.6
/cherry-pick release-1.5

2024-03-19 11:03 UTC, Sunnatillo commented
/cherry-pick release-1.5