🌱 Update flag names to align with k8s components
metal3-io/cluster-api-provider-metal3 pull request #158
Opened 2021-02-09 10:17 UTC by fmuyassarov

**What this PR does / why we need it**:
Update flag names to align with K8S components. These flags have been renamed in [K8S](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/) and CAPI as well, and we would anyways need to rename them in the future to avoid future breaks when switching to CAPI v1alpah4 from v1alpha3.
The flag changes is one of the changes listed in the [Cluster API v1alpha3 compared to v1alpha4](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md#align-manager-flag-names-with-upstream-kubernetes-components)

`--metrics-addr`  to  `--metrics-bind-addr`
`--leader-election`  to  `--leader-elect`

To see the changes in CAPI from v1alpha3 -> v1alpha4, see the [doc](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md#align-manager-flag-names-with-upstream-kubernetes-components)

2021-02-09 10:18 UTC, fmuyassarov commented
/cc @maelk 
/cc @kashifest 
/test-integration

2021-02-09 11:08 UTC, kashifest approved these changes

2021-02-09 11:08 UTC, kashifest commented
/test-centos-integration
/test-v1a3-centos-integration
No logic to test these, but just to be sure ...

2021-02-09 11:11 UTC, furkatgofurov7 requested changes
As per your patch description:

2021-02-09 11:11 UTC, furkatgofurov7 commented on config/manager/manager_auth_proxy_patch.yaml
> +        - "--metrics-bind-address=127.0.0.1:8080"
```suggestion
        - "--metrics-bind-addr=127.0.0.1:8080"
```

2021-02-09 11:11 UTC, furkatgofurov7 commented on config/webhook/manager_webhook_patch.yaml
> +          - "--metrics-bind-address=127.0.0.1:8080"
same

2021-02-09 11:11 UTC, furkatgofurov7 commented on main.go
> +	flag.StringVar(&metricsAddr, "metrics-bind-address", ":8080", "The address the metric endpoint binds to.")
same

2021-02-09 11:36 UTC, fmuyassarov commented
> As per your patch description:



> As per your patch description:

Updated the description.

2021-02-09 11:39 UTC, fmuyassarov commented
@furkatgofurov7 reference document just in case
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/

2021-02-09 12:05 UTC, furkatgofurov7 commented
> @furkatgofurov7 reference document just in case
> https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/

Okay, this is a reference to kube-proxy btw, not kube-controller-manager.

2021-02-09 12:34 UTC, fmuyassarov commented
> /test-v1a3-centos-integration

Seems we caught the problem 😀

2021-02-09 12:51 UTC, fmuyassarov commented
> > @furkatgofurov7 reference document just in case
> > https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/
> 
> Okay, this is a reference to kube-proxy btw, not kube-controller-manager. I was checking the latter one initially.

you are right

2021-02-09 13:35 UTC, fmuyassarov commented
/hold until the decision is made how we progress with CAPI v1alpha4 changes

2021-02-09 13:40 UTC, maelk commented
You cannot use the v1a3 job on a PR that is towards CAPM3 master, as this is v1a4!

2021-02-09 13:41 UTC, kashifest commented
> You cannot use the v1a3 job on a PR that is towards CAPM3 master, as this is v1a4!

Ah, true!

2021-02-09 13:42 UTC, kashifest commented
The reason of failure is something else @fmuyassarov

2021-02-09 13:44 UTC, fmuyassarov commented
> The reason of failure is something else @fmuyassarov

I think the reason is what @maelk mentioned. Because, I can see that there are two deployments of BMO, + CAPM3 is v1alpha4

```
[airshipci@ci-test-vm-20210209123434-gotb ~]$ kubectl get pods -A
NAMESPACE                           NAME                                                             READY   STATUS    RESTARTS   AGE
baremetal-operator-system           baremetal-operator-controller-manager-66b4fd8b65-56hkj           2/2     Running   0          29m
capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-controller-manager-ddcc95784-6mlxf        2/2     Running   0          28m
capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-controller-manager-d85dfd44c-4pg22    2/2     Running   0          28m
capi-system                         capi-controller-manager-5cd969bf55-mll24                         2/2     Running   0          28m
capi-webhook-system                 capi-controller-manager-68c9ff8646-pqqvz                         2/2     Running   0          28m
capi-webhook-system                 capi-kubeadm-bootstrap-controller-manager-7cf85756c5-kk249       2/2     Running   0          28m
capi-webhook-system                 capi-kubeadm-control-plane-controller-manager-7854964ff4-59m2w   2/2     Running   0          28m
capi-webhook-system                 capm3-controller-manager-6694579588-stvlp                        2/2     Running   0          28m
capi-webhook-system                 capm3-ipam-controller-manager-b75477967-6wm26                    2/2     Running   0          28m
capm3-system                        capm3-baremetal-operator-controller-manager-6b864d6b8d-d2thv     2/2     Running   0          28m
capm3-system                        capm3-controller-manager-5978456464-967px                        2/2     Running   0          28m
capm3-system                        capm3-ipam-controller-manager-5b4bd5c94b-xxlvz                   2/2     Running   0          28m
cert-manager                        cert-manager-cainjector-fc6c787db-2gj2h                          1/1     Running   0          28m
cert-manager                        cert-manager-d994d94d7-qp4zg                                     1/1     Running   0          28m
cert-manager                        cert-manager-webhook-845d9df8bf-968lw                            1/1     Running   0          28m
kube-system                         coredns-74ff55c5b-vdg6p                                          1/1     Running   0          29m
kube-system                         etcd-minikube                                                    1/1     Running   1          39m
kube-system                         kube-apiserver-minikube                                          1/1     Running   1          39m
kube-system                         kube-controller-manager-minikube                                 1/1     Running   1          39m
kube-system                         kube-proxy-ws8qm                                                 1/1     Running   0          29m
kube-system                         kube-scheduler-minikube                                          1/1     Running   1          39m
kube-system                         storage-provisioner                                              1/1     Running   1          39m
metal3                              metal3-ironic-5cb45dd9f6-82fmg                                   9/9     Running   0          28m

```



```
[airshipci@ci-test-vm-20210209123434-gotb ~]$ kubectl api-resources
NAME                              SHORTNAMES                APIVERSION                                 NAMESPACED   KIND
bindings                                                    v1                                         true         Binding
componentstatuses                 cs                        v1                                         false        ComponentStatus
configmaps                        cm                        v1                                         true         ConfigMap
endpoints                         ep                        v1                                         true         Endpoints
events                            ev                        v1                                         true         Event
limitranges                       limits                    v1                                         true         LimitRange
namespaces                        ns                        v1                                         false        Namespace
nodes                             no                        v1                                         false        Node
persistentvolumeclaims            pvc                       v1                                         true         PersistentVolumeClaim
persistentvolumes                 pv                        v1                                         false        PersistentVolume
pods                              po                        v1                                         true         Pod
podtemplates                                                v1                                         true         PodTemplate
replicationcontrollers            rc                        v1                                         true         ReplicationController
resourcequotas                    quota                     v1                                         true         ResourceQuota
secrets                                                     v1                                         true         Secret
serviceaccounts                   sa                        v1                                         true         ServiceAccount
services                          svc                       v1                                         true         Service
challenges                                                  acme.cert-manager.io/v1beta1               true         Challenge
orders                                                      acme.cert-manager.io/v1beta1               true         Order
clusterresourcesetbindings                                  addons.cluster.x-k8s.io/v1alpha3           true         ClusterResourceSetBinding
clusterresourcesets                                         addons.cluster.x-k8s.io/v1alpha3           true         ClusterResourceSet
mutatingwebhookconfigurations                               admissionregistration.k8s.io/v1            false        MutatingWebhookConfiguration
validatingwebhookconfigurations                             admissionregistration.k8s.io/v1            false        ValidatingWebhookConfiguration
customresourcedefinitions         crd,crds                  apiextensions.k8s.io/v1                    false        CustomResourceDefinition
apiservices                                                 apiregistration.k8s.io/v1                  false        APIService
controllerrevisions                                         apps/v1                                    true         ControllerRevision
daemonsets                        ds                        apps/v1                                    true         DaemonSet
deployments                       deploy                    apps/v1                                    true         Deployment
replicasets                       rs                        apps/v1                                    true         ReplicaSet
statefulsets                      sts                       apps/v1                                    true         StatefulSet
tokenreviews                                                authentication.k8s.io/v1                   false        TokenReview
localsubjectaccessreviews                                   authorization.k8s.io/v1                    true         LocalSubjectAccessReview
selfsubjectaccessreviews                                    authorization.k8s.io/v1                    false        SelfSubjectAccessReview
selfsubjectrulesreviews     [...]

2021-02-09 13:47 UTC, fmuyassarov commented
/test-integration

2021-02-09 13:48 UTC, kashifest commented
> I think the reason is what @maelk mentioned. Because, I can see that there are two deployments of BMO, + CAPM3 is v1alpha4
Yes I got it now

2021-02-28 17:36 UTC, fmuyassarov commented
/test golint

2021-02-28 17:38 UTC, fmuyassarov commented
/test-integration

2021-02-28 22:29 UTC, fmuyassarov commented
/test-integration

2021-03-09 08:52 UTC, fmuyassarov commented
/test-integration

2021-03-13 13:45 UTC, fmuyassarov commented
/test-integration

2021-06-23 16:06 UTC, fmuyassarov commented
/test-v1a5-e2e

2021-06-23 16:07 UTC, fmuyassarov commented
/test-v1a5-e2e

2021-06-23 16:11 UTC, fmuyassarov commented
/test-v1a5-e2e

2021-07-07 20:17 UTC, fmuyassarov commented
/close

2021-07-08 14:03 UTC, furkatgofurov7 commented
/override markdownlint

2021-07-08 14:03 UTC, fmuyassarov commented
/override markdownlint

2021-07-08 14:03 UTC, fmuyassarov commented
/override

2021-07-08 14:04 UTC, closed without merging