Redundant IP claims and related RBAC policies
metal3-io/cluster-api-provider-metal3 pull request #2056
Opened 2024-10-28 15:02 UTC by ksahil12

Removed RBAC rules are not being utilized by operator and hence can be cleaned up. It includes:
1. ipclaims
2. ipaddresses
3. ipaddressclaims

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

2024-10-28 15:15 UTC, tuminoid commented
/ok-to-test
/test metal3-centos-e2e-integration-test-main 

Please sign off the commit to pass DCO.

/cc @kashifest

2024-10-30 08:00 UTC, Rozzii commented
/retest

2024-10-30 08:24 UTC, Rozzii requested changes
I don't think this is actually correct.
/hold

2024-10-30 08:40 UTC, adilGhaffarDev commented
> I don't think this is actually correct.
> These comments are not in the file that I would expect them to be but they are also no repeated elswhere.
> Simply deleting them won't be enough, I will look into this in a bit more detail.

@ksahil12 you have to run "make generate" after removing the comments, this will update rbacs in the config. However, I think this change will break CAPM3 because we need these rbacs in Metal3Data.

2024-10-30 08:50 UTC, Rozzii commented
After looking into it a bit more, these are package level kubebuilder tags: https://book.kubebuilder.io/reference/markers/rbac.html .
Functionally nothing would change if we would move these commands to a different file, and these tags are certainly not redundant this is the only place where they are listed.

This change would only make sense if the tags would be moved to an other .go file within the package where the IPAM related resources are actually accessed  but even then it would be just a syntax change no functional change .

Also just by removing the kubebuilder tag commands without running "make generate" on the repo, the actual RBAC boilerplate coud wouldn't be generated.

2024-12-23 06:55 UTC, adilGhaffarDev commented
> After looking into it a bit more, these are package level kubebuilder tags: https://book.kubebuilder.io/reference/markers/rbac.html . Functionally nothing would change if we would move these commands to a different file, and these tags are certainly not redundant this is the only place where they are listed.
> 
> This change would only make sense if the tags would be moved to an other .go file within the package where the IPAM related resources are actually accessed but even then it would be just a syntax change no functional change .
> 
> Also just by removing the kubebuilder tag commands without running "make generate" on the repo, the actual RBAC boilerplate code wouldn't be re-generated.

Closing this in support of this

2024-12-23 06:55 UTC, closed without merging