✨ Use correct aliases for camp3 api
metal3-io/cluster-api-provider-metal3 pull request #241
Opened 2021-07-05 14:55 UTC by fmuyassarov

**What this PR does / why we need it**:
We don't have v1 APIs yet, so let's be explicit.

2021-07-05 14:56 UTC, fmuyassarov commented
/cc @furkatgofurov7 
/cc @Xenwar 
/test-integration

2021-07-06 09:24 UTC, fmuyassarov commented
/cc @maelk

2021-07-06 09:35 UTC, furkatgofurov7 requested changes

2021-07-06 09:35 UTC, furkatgofurov7 commented on main.go
> +	infrav1alpha5alpha4 "github.com/metal3-io/cluster-api-provider-metal3/api/v1alpha4"
typo

2021-07-06 09:35 UTC, furkatgofurov7 commented on main.go
> +	_ = infrav1alpha5alpha4.AddToScheme(myscheme)
same

2021-07-06 10:01 UTC, fmuyassarov commented on main.go
> +	infrav1alpha5alpha4 "github.com/metal3-io/cluster-api-provider-metal3/api/v1alpha4"
thanks, fixed

2021-07-06 10:02 UTC, fmuyassarov commented
/test-integration

2021-07-06 10:32 UTC, furkatgofurov7 reviewed
Since this is just a cosmetic change, approving. 

/approve

2021-07-06 13:33 UTC, furkatgofurov7 commented
/retitle ✨ Use correct aliases for capm3 api

2021-07-07 09:10 UTC, lentzi90 approved these changes

2021-07-07 18:53 UTC, fmuyassarov commented
/cc @jan-est

2021-07-08 06:12 UTC, jan-est commented
/lgtm

2021-07-08 06:12 UTC, merged