🐛 Parameterize the CAPI and CAPM3 version in the e2e config file
metal3-io/cluster-api-provider-metal3 pull request #243
Opened 2021-07-07 13:09 UTC by namnx228

**What this PR does / why we need it**:
This PR makes the CAPI and CAPM3 versions defined in e2e config file the same with the version we use to setup the management cluster. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

2021-07-07 13:11 UTC, namnx228 commented
/test-integration
/test-v1a5-e2e
/assign @furkatgofurov7 
/cc @wgslr

2021-07-07 13:18 UTC, wgslr commented
The e2e changes look good to me, but why is it a merge commit and has the removal of dhellmann in the diff?

2021-07-07 13:26 UTC, namnx228 commented
> The e2e changes look good to me, but why is it a merge commit and has the removal of dhellmann in the diff?

Ouch, good catch. Fixed. Thanks

2021-07-07 13:26 UTC, namnx228 commented
/test-integration
/test-v1a5-e2e

2021-07-07 13:28 UTC, furkatgofurov7 requested changes

2021-07-07 13:28 UTC, furkatgofurov7 commented on test/e2e/config/e2e_conf.yaml
>          value: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.3.17/bootstrap-components.yaml"
same applies as above

2021-07-07 13:28 UTC, furkatgofurov7 commented on test/e2e/config/e2e_conf.yaml
>          value: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.3.17/control-plane-components.yaml"
same

2021-07-07 13:29 UTC, furkatgofurov7 commented on test/e2e/config/e2e_conf.yaml
>          value: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.3.17/core-components.yaml"
```suggestion
        value: "https://github.com/kubernetes-sigs/cluster-api/releases/download/${CAPIRELEASE}/core-components.yaml"
```

2021-07-07 13:34 UTC, namnx228 commented
/test-integration
/test-v1a5-e2e

2021-07-07 14:25 UTC, furkatgofurov7 commented
From the CI e2e test logs:
```
`INFO: Waiting for control plane to be ready
INFO: Waiting for the remaining control plane machines managed by metal3/test1 to be provisioned
STEP: Waiting for all control plane nodes to exist
INFO: Failed to list the machines: Get "https://127.0.0.1:34607/apis/cluster.x-k8s.io/v1alpha3/namespaces/metal3/machines?labelSelector=cluster.x-k8s.io%2Fcluster-name%3Dtest1%2Ccluster.x-k8s.io%2Fcontrol-plane%3D": EOF
INFO: Failed to list the machines: Get "https://127.0.0.1:34607/apis/cluster.x-k8s.io/v1alpha3/namespaces/metal3/machines?labelSelector=cluster.x-k8s.io%2Fcluster-name%3Dtest1%2Ccluster.x-k8s.io%2Fcontrol-plane%3D": EOF
INFO: Failed to list the machines: Get "https://127.0.0.1:34607/apis/cluster.x-k8s.io/v1alpha3/namespaces/metal3/machines?labelSelector=cluster.x-k8s.io%2Fcluster-name%3Dtest1%2Ccluster.x-k8s.io%2Fcontrol-plane%3D": EOF
INFO: Got error while streaming logs for pod capi-webhook-system/capm3-controller-manager-6f4d595bff-j8khd, container kube-rbac-proxy: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capi-webhook-system/capi-kubeadm-bootstrap-controller-manager-7cd999d68c-dvtnv, container kube-rbac-proxy: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capi-webhook-system/capi-kubeadm-control-plane-controller-manager-5f94c6cc46-5kkrw, container manager: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capi-webhook-system/capm3-ipam-controller-manager-686f54975c-vbhmz, container kube-rbac-proxy: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capm3-system/capm3-controller-manager-6d4ddddc65-52vk8, container kube-rbac-proxy: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capi-webhook-system/capm3-ipam-controller-manager-686f54975c-vbhmz, container kube-rbac-proxy: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capi-webhook-system/capi-controller-manager-5bfbf6dcfd-h5m5d, container kube-rbac-proxy: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capi-webhook-system/capi-kubeadm-control-plane-controller-manager-5f94c6cc46-5kkrw, container kube-rbac-proxy: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capi-webhook-system/capm3-controller-manager-6f4d595bff-j8khd, container manager: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capm3-system/capm3-controller-manager-6d4ddddc65-52vk8, container kube-rbac-proxy: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capi-kubeadm-bootstrap-system/capi-kubeadm-bootstrap-controller-manager-6fd7bb7948-lz4hc, container kube-rbac-proxy: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capi-system/capi-controller-manager-8645d98955-nmgt8, container kube-rbac-proxy: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capm3-system/capm3-baremetal-operator-controller-manager-7fd6769dc5-vb7wt, container kube-rbac-proxy: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capi-webhook-system/capm3-ipam-controller-manager-686f54975c-vbhmz, container manager: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capi-kubeadm-control-plane-system/capi-kubeadm-control-plane-controller-manager-657796cdc9-49h8m, container kube-rbac-proxy: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capm3-system/capm3-ipam-controller-manager-6b77b87b46-2drcg, container kube-rbac-proxy: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capi-webhook-system/capm3-controller-manager-6f4d595bff-j8khd, container manager: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capm3-system/capm3-ipam-controller-manager-6b77b87b46-2drcg, container kube-rbac-proxy: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capi-webhook-system/capi-controller-manager-5bfbf6dcfd-h5m5d, container manager: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capm3-system/capm3-ipam-controller-manager-6b77b87b46-2drcg, container kube-rbac-proxy: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capi-webhook-system/capm3-controller-manager-6f4d595bff-j8khd, container kube-rbac-proxy: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capi-webhook-system/capi-kubeadm-bootstrap-controller-manager-7cd999d68c-dvtnv, container manager: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capm3-system/capm3-controller-manager-6d4ddddc65-52vk8, container kube-rbac-proxy: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Got error while streaming logs for pod capi-webhook-system/capm3-ipam-controller-manager-686f54975c-vbhmz, container manager: http2: server sent GOAWAY and closed the connection; LastStreamID=3917, ErrCode=NO_ERROR, debug=""
INFO: Failed to list the machines: an error on the server ("") has prevented the request from succeeding (get machines.cluster.x-k8s.io)`
```
which I have not seen in previous runs. Even though it passed, re-triggering the test to double check if it is one time flake or something is going wrong with these changes. 

/test-v1a5-e2e

2021-07-07 14:26 UTC, furkatgofurov7 commented
/test-v1a5-e2e

2021-07-07 15:56 UTC, furkatgofurov7 reviewed
That was one time flake, should be fine now. 

/approve

2021-07-08 05:43 UTC, lentzi90 approved these changes

2021-07-08 06:05 UTC, jan-est commented
/lgtm

2021-07-08 06:05 UTC, merged