📖update architecture doc per current output
metal3-io/cluster-api-provider-metal3 pull request #270
Opened 2021-08-18 09:07 UTC by jichenjc

**What this PR does / why we need it**:

some of the existing doc output is incorrect per test result

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

2021-08-23 10:00 UTC, furkatgofurov7 commented
/ok-to-test

2021-08-23 10:02 UTC, furkatgofurov7 commented
Thanks for the PR @jichenjc! Please fix the markdown issue, and we can trigger mandatory integration test. Thank you.

2021-08-24 06:39 UTC, jichenjc commented
@furkatgofurov7 thanks~, updated

2021-08-24 06:48 UTC, furkatgofurov7 commented
/test-integration

2021-08-24 06:59 UTC, furkatgofurov7 commented
@jichenjc I just noticed there are few more places in the same documentation where it needs an update in terms of API versions(all CAPI objects should have `v1alpha4` and CAPM3 objects `v1alpha5` API versions). It would be great, if you could take care of updating those in the same PR.

2021-08-25 08:08 UTC, jichenjc commented
@furkatgofurov7 updated again :)

2021-08-25 11:42 UTC, furkatgofurov7 requested changes
Thanks, there is only one mention of API for Metal3Cluster that is left still in line 131 that needs an update.

2021-08-31 19:23 UTC, furkatgofurov7 commented
/test-integration
/lgtm
/cc @kashifest

2021-09-08 07:54 UTC, fmuyassarov approved these changes

2021-09-08 08:14 UTC, kashifest approved these changes

2021-09-08 08:14 UTC, kashifest commented on docs/architecture.md
> +  |# UserData comes from 'Metal3Machine' and is added by 'CAPBK'               |
Is it still called CAPBK?

2021-09-08 08:15 UTC, merged