Add description for NoCloudProvider
metal3-io/cluster-api-provider-metal3 pull request #374
Opened 2021-11-09 06:17 UTC by Xenwar

Add description for NoCloudProvider
The description is visible with kubectl explain m3mcluster.spec.NoCloudProvider

2021-11-09 06:19 UTC, Xenwar commented
/test-v1b1-integration

2021-11-09 06:34 UTC, Xenwar commented
/test gofmt

2021-11-09 06:34 UTC, Xenwar commented
/test unit

2021-11-09 06:38 UTC, Xenwar commented
/retest

2021-11-09 06:40 UTC, Xenwar commented
/retest

2021-11-09 06:47 UTC, Xenwar commented
/test unit
/test manifestlint
/test gofmt
/test govet

2021-11-09 06:47 UTC, Xenwar commented
/test-v1b1-integration

2021-11-09 06:49 UTC, Xenwar commented
/test govet

2021-11-09 06:56 UTC, Xenwar commented
/test manifestlint

2021-11-09 07:23 UTC, Xenwar commented
/test unit

2021-11-09 07:24 UTC, Xenwar commented
/test gofmt

2021-11-09 08:09 UTC, Xenwar commented
/test-v1b1-integration

2021-11-09 09:12 UTC, Xenwar commented
/test-v1b1-integration

2021-11-09 09:16 UTC, Xenwar commented
/assign @maelk

2021-11-10 07:33 UTC, Xenwar commented
/test-v1b1-integration

2021-11-10 08:31 UTC, kashifest requested changes

2021-11-10 08:31 UTC, kashifest commented on api/v1alpha4/metal3cluster_types.go
> +	// If set to false, providerID is set nodes by other entities and CAPM3 uses the value to the providerID on the m3m resource.
```suggestion
	// If set to false, providerID is set on nodes by other entities and CAPM3 uses the value of the providerID on the m3m resource.
```

2021-11-10 08:31 UTC, kashifest commented on api/v1alpha5/metal3cluster_types.go
> +	// If set to false, providerID is set nodes by other entities and CAPM3 uses the value to the providerID on the m3m resource.
Same comment as above

2021-11-10 08:31 UTC, kashifest commented on api/v1beta1/metal3cluster_types.go
> +	// If set to false, providerID is set nodes by other entities and CAPM3 uses the value to the providerID on the m3m resource.
same

2021-11-10 11:14 UTC, Xenwar commented on api/v1alpha4/metal3cluster_types.go
> +	// Determnes if the cluster will not be deployed with an external cloud provider.
Thanks, done.

2021-11-10 11:15 UTC, Xenwar commented on api/v1alpha4/metal3cluster_types.go
> +	// If set to false, providerID is set nodes by other entities and CAPM3 uses the value to the providerID on the m3m resource.
Thanks, done.

2021-11-10 11:15 UTC, Xenwar commented on api/v1alpha5/metal3cluster_types.go
> +	// If set to false, providerID is set nodes by other entities and CAPM3 uses the value to the providerID on the m3m resource.
Thanks, done.

2021-11-10 11:15 UTC, Xenwar commented on api/v1beta1/metal3cluster_types.go
> +	// If set to false, providerID is set nodes by other entities and CAPM3 uses the value to the providerID on the m3m resource.
Thanks, done.

2021-11-10 11:54 UTC, Xenwar commented
/test-v1b1-integration

2021-11-11 11:51 UTC, Xenwar commented
//test-v1b1-integration

2021-11-11 11:56 UTC, furkatgofurov7 commented
/test-v1b1-integration

2021-11-11 12:05 UTC, furkatgofurov7 commented
/retitle 🌱 Add description to m3cluster NoCloudProvider boolean field
/lgtm

2021-11-16 13:33 UTC, kashifest commented
/test-v1b1-integration
/approve
/lgtm
Adding lgtm since, it was added before by @furkatgofurov7

2021-11-16 14:15 UTC, merged