📖 Add pivoting and provider installation instructions
metal3-io/cluster-api-provider-metal3 pull request #377
Opened 2021-11-11 15:08 UTC by fmuyassarov

**What this PR does / why we need it**:
Add pivoting and provider installation instructions

2021-11-11 19:05 UTC, kashifest reviewed
Thanks for the writeup. Mostly good. Few suggestions inline. I'll approve and add a hold for few more reviews. Please unhold when you think its ready to go in.
/approve
/hold

2021-11-11 19:05 UTC, kashifest commented on README.md
> +1. Install Metal3 provider. This will install Cluster-api-provider Metal3 CRDs and controllers
```suggestion
1. Install Metal3 provider. This will install Cluster-api-provider Metal3 CRDs and controllers.
```

2021-11-11 19:05 UTC, kashifest commented on README.md
> +1. Install Baremetal Operator and its CRD. You need to install cert-manager for Baremetal Operator,
```suggestion
1. Deploy Baremetal Operator manifests and CRDs. You need to install cert-manager for Baremetal Operator,
```

2021-11-11 19:05 UTC, kashifest commented on README.md
> +on the BareMetalHost CRD before pivoting.
```suggestion
on the BareMetalHost CRD before pivoting. If other CRDs also need to be pivoted to target cluster we need to add the same label in the CRDs. 
```

2021-11-12 09:10 UTC, fmuyassarov commented
@kashifest thanks for the review. I have the same changes for release-0.5 branch in https://github.com/metal3-io/cluster-api-provider-metal3/pull/378. PTAL.

2021-11-12 09:23 UTC, fmuyassarov commented
/test all

2021-11-12 10:51 UTC, fmuyassarov commented
/test unit

2021-11-12 10:53 UTC, fmuyassarov commented
/test-v1b1-integration

2021-11-12 10:55 UTC, furkatgofurov7 requested changes

2021-11-12 10:55 UTC, furkatgofurov7 commented on README.md
> +[Clusterctl](https://master.cluster-api.sigs.k8s.io/clusterctl/overview.html).
please revert this back, old URL seems right already

2021-11-12 10:57 UTC, fmuyassarov commented
/test-v1b1-integration

2021-11-12 10:57 UTC, furkatgofurov7 reviewed
/lgtm

2021-11-12 12:05 UTC, fmuyassarov commented
/hold cancel

2021-11-12 12:06 UTC, merged

2021-11-14 07:34 UTC, fmuyassarov commented
/cherry-pick release-0.5

2021-11-14 07:34 UTC, fmuyassarov commented
/cherry-pick release-0.4

2021-11-14 07:51 UTC, fmuyassarov commented
/cherry-pick release-0.4

2021-11-14 08:06 UTC, fmuyassarov commented
/cherry-pick release-0.4