🌱 metal3remediation_manager unit tests
metal3-io/cluster-api-provider-metal3 pull request #546
Opened 2022-03-02 16:05 UTC by adilGhaffarDev

This PR adds following unit tests for metal3remediation_manager:

- GetUnhealthyHost (new entries added)
- SetUnhealthyAnnotation
- SetRebootAnnotation
- TimeToRemediate

74% coverage is done.

2022-03-22 10:36 UTC, adilGhaffarDev commented
/test golangci-lint

2022-03-25 15:10 UTC, smoshiur1237 requested changes
Thanks for the unit tests entries. Initial review is done. Please add the coverage info in the PR description.

2022-03-25 15:10 UTC, smoshiur1237 commented on baremetal/metal3remediation_manager_test.go
> +		Entry("Should not set the unhealthy annotation,  annotation not present", testCaseSetUnhealthyAnnotation{
```suggestion
		Entry("Should not set the unhealthy annotation,  annotation is empty", testCaseSetUnhealthyAnnotation{
```

2022-03-25 15:10 UTC, smoshiur1237 commented on baremetal/metal3remediation_manager_test.go
> +		Entry("Should not set the unhealthy annotation, should not find unhealthy host", testCaseSetUnhealthyAnnotation{
```suggestion
		Entry("Should not set the unhealthy annotation because of wrong HostAnnotation", testCaseSetUnhealthyAnnotation{
```

2022-03-25 15:10 UTC, smoshiur1237 commented on baremetal/metal3remediation_manager_test.go
> +		Entry("Should not set the reboot annotation,  annotation not present", testCaseSetUnhealthyAnnotation{
```suggestion
		Entry("Should not set the reboot annotation,  annotation is empty", testCaseSetUnhealthyAnnotation{
```

2022-03-25 15:10 UTC, smoshiur1237 commented on baremetal/metal3remediation_manager_test.go
> +		Entry("Should not set the reboot annotation, should not find unhealthy host", testCaseSetUnhealthyAnnotation{
```suggestion
		Entry("Should not set the reboot annotation because of wrong HostAnnotation", testCaseSetUnhealthyAnnotation{
```

2022-03-25 15:10 UTC, smoshiur1237 commented on baremetal/metal3remediation_manager_test.go
> +		Entry("Time to remediate is not reached, LastRemediated not present", testTimeToRemediate{
```suggestion
		Entry("Time to remediate is not reached because of  LastRemediated is nil", testTimeToRemediate{
```

2022-03-25 15:10 UTC, smoshiur1237 commented on baremetal/metal3remediation_manager_test.go
> +		Entry("Time to remediate is not reached", testTimeToRemediate{
The message is not clear and needs reason

2022-03-31 10:29 UTC, Sunnatillo reviewed
looks good to me

2022-03-31 10:29 UTC, Sunnatillo commented on baremetal/metal3remediation_manager_test.go
> +		Entry("Should not set the reboot annotation, annotation is emoty", testCaseSetUnhealthyAnnotation{
there is typo, please fix if you can

2022-04-01 07:17 UTC, Sunnatillo approved these changes
LGTM

2022-04-04 08:50 UTC, smoshiur1237 commented
/test-v1b1-ubuntu-integration

2022-04-04 08:52 UTC, smoshiur1237 approved these changes
/lgtm

2022-04-04 11:12 UTC, adilGhaffarDev commented
/assign @furkatgofurov7

2022-04-05 11:57 UTC, furkatgofurov7 reviewed
Good job overall looks good, some concerns/suggestions inline:

2022-04-05 11:57 UTC, furkatgofurov7 commented on baremetal/metal3remediation_manager_test.go
> +					Annotations: map[string]string{capm3.UnhealthyAnnotation: ""},
Why are we setting UnhealthyAnnotation when test entry is all about reboot annotation?

2022-04-05 11:57 UTC, furkatgofurov7 commented on baremetal/metal3remediation_manager_test.go
> +					Annotations: map[string]string{capm3.UnhealthyAnnotation: ""},
same here in other entries

2022-04-05 11:57 UTC, furkatgofurov7 commented on baremetal/metal3remediation_manager_test.go
> +
nit: extra new line

2022-04-05 11:57 UTC, furkatgofurov7 commented on baremetal/metal3remediation_manager_test.go
> +
nit: extra new line

2022-04-05 11:57 UTC, furkatgofurov7 commented on baremetal/metal3remediation_manager_test.go
> +		Entry("Should not find the host, host annotation is empty", testCaseGetUnhealthyHost{
It is not host annotation but rather m3m if you wanna specify, otherwise should be fine as is

2022-04-05 11:57 UTC, furkatgofurov7 commented on baremetal/metal3remediation_manager_test.go
> +
nit: extra new line

2022-04-06 10:53 UTC, furkatgofurov7 commented
/test-v1b1-ubuntu-integration

2022-04-06 10:54 UTC, furkatgofurov7 approved these changes
/approve

2022-04-06 10:54 UTC, furkatgofurov7 commented
/cc @kashifest @smoshiur1237

2022-04-06 11:09 UTC, Sunnatillo approved these changes
LGTM

2022-04-06 12:21 UTC, furkatgofurov7 commented
/test all

2022-04-06 15:25 UTC, furkatgofurov7 commented
/test-v1b1-ubuntu-integration

2022-04-06 16:34 UTC, furkatgofurov7 commented
Considering lgtm label was removed after rebase, lgtm'ing again to take this in.

/lgtm

2022-04-06 20:06 UTC, furkatgofurov7 commented
/retest

2022-04-06 20:06 UTC, furkatgofurov7 commented
/test all

2022-04-07 06:00 UTC, kashifest commented
/retest

2022-04-07 06:00 UTC, kashifest commented
/test all

2022-04-07 07:25 UTC, kashifest commented
/test all

2022-04-07 08:56 UTC, kashifest commented
/hold

2022-04-07 10:32 UTC, kashifest commented
closing it since #597 got merged

2022-04-07 10:32 UTC, closed without merging