🌱 uplift k8s to 1.24.0
metal3-io/cluster-api-provider-metal3 pull request #615
Opened 2022-05-04 08:45 UTC by adilGhaffarDev

Uplift k8s to 1.24.0

2022-07-01 16:37 UTC, mboukhalfa commented
/test-v1b1-ubuntu-integration

2022-07-11 08:57 UTC, furkatgofurov7 commented
Will be removed, this is to test CI behaviour. 

/hold

2022-07-13 11:56 UTC, furkatgofurov7 requested changes
This is missing to address this https://github.com/metal3-io/metal3-dev-env/issues/898#issuecomment-1018457872 comment

2022-07-13 12:19 UTC, adilGhaffarDev commented
> This is missing to address this [metal3-io/metal3-dev-env#898 (comment)](https://github.com/metal3-io/metal3-dev-env/issues/898#issuecomment-1018457872) comment

I am adding this.

2022-07-13 21:55 UTC, furkatgofurov7 requested changes

2022-07-13 21:55 UTC, furkatgofurov7 commented on scripts/environment.sh
>  export FROM_K8S_VERSION="v1.23.5"
```suggestion
export FROM_K8S_VERSION="v1.23.8"
```

2022-07-13 21:55 UTC, furkatgofurov7 commented on test/e2e/config/e2e_conf.yaml
>    KUBERNETES_VERSION: "v1.23.5"
```suggestion
  KUBERNETES_VERSION: "v1.23.8"
```

2022-07-18 07:32 UTC, furkatgofurov7 commented
/test-e2e-ubuntu-main
/test-e2e-centos-main

2022-07-18 07:49 UTC, furkatgofurov7 commented
/test-ubuntu-e2e-main
/test-centos-e2e-main

2022-07-18 07:51 UTC, furkatgofurov7 commented
/test-upgrade-e2e-main

2022-07-18 11:24 UTC, adilGhaffarDev commented
/test-ubuntu-e2e-main
/test-centos-e2e-main

2022-07-18 11:25 UTC, adilGhaffarDev commented
/test-upgrade-e2e-main

2022-07-18 13:57 UTC, adilGhaffarDev commented
/keep-test-centos-e2e-main

2022-07-18 22:15 UTC, furkatgofurov7 commented
/test-ubuntu-e2e-main
/test-centos-e2e-main

2022-07-19 00:18 UTC, furkatgofurov7 commented
/test-ubuntu-e2e-main
/test-centos-e2e-main

2022-07-19 07:04 UTC, adilGhaffarDev commented
/test-ubuntu-e2e-main
/test-centos-e2e-main

2022-07-19 08:45 UTC, adilGhaffarDev commented
/test-ubuntu-e2e-main
/test-centos-e2e-main

2022-07-19 08:56 UTC, adilGhaffarDev commented
/test-ubuntu-e2e-main
/test-centos-e2e-main

2022-07-19 10:38 UTC, adilGhaffarDev commented
/test-ubuntu-e2e-main
/test-centos-e2e-main

2022-07-19 12:00 UTC, adilGhaffarDev commented
/test-ubuntu-e2e-main
/test-centos-e2e-main

2022-07-19 12:06 UTC, furkatgofurov7 commented
/test-ubuntu-e2e-main
/test-centos-e2e-main

2022-07-19 16:40 UTC, furkatgofurov7 commented
/cc @fmuyassarov

2022-07-19 16:41 UTC, furkatgofurov7 commented
/test-centos-integration-main

2022-07-20 07:04 UTC, fmuyassarov reviewed
/lgtm

2022-07-20 07:05 UTC, merged