✨  refactor providerID duplicate checks
metal3-io/cluster-api-provider-metal3 pull request #616
Opened 2022-05-04 12:48 UTC by Xenwar

refactor providerID duplicate checks

ProviderID duplicate check is broken into two. 
`currentProviderIDUsedMultipleTimes` is run during provisioning of a node. If focuses on a single providerID. To see if it is being used in different formats. 

`duplicateProviderIDsExist` can be run at any time. The purpose of it is to detect duplicates introduced either manually or due to Manual modification of cloud init dataor an isolated/dead node rejoining a cluster.

Fixes #589

2022-05-04 13:54 UTC, smoshiur1237 requested changes
Few changes needed for nits.  I think it should include the unit test with the same PR.

2022-05-04 13:54 UTC, smoshiur1237 commented on baremetal/metal3machine_manager.go
> +		// duplicates due to the same, at least, two instances of legacy OR new OR unknown formats being used in multiple nodes.
```suggestion
		// verify if same providerID is used by multiple nodes.
```

2022-05-04 18:11 UTC, Xenwar commented on baremetal/metal3machine_manager.go
> +		errMsg := fmt.Sprintf("both formats of providerID (%s and %s) cannot be used at the same time by node(s): (%s)", providerIDLegacy, providerIDNew, duplicateNodesNames)
done

2022-05-04 18:11 UTC, Xenwar commented on baremetal/metal3machine_manager.go
> +// this can be called at any time.
removed

2022-05-04 18:11 UTC, Xenwar commented on baremetal/metal3machine_manager.go
> +// providerIDUsedMultipleTimes determnes if a providerID is already in use in different formats.
fixed

2022-05-04 18:11 UTC, Xenwar commented on baremetal/metal3machine_manager.go
> +			errMsg := fmt.Sprintf("providerID %s is in use by multiple nodes: (%s)", providerID, matchingNodes)
fixed

2022-05-04 18:13 UTC, Xenwar commented on baremetal/metal3machine_manager.go
> +// duplicateProviderIDsExist determnes if a providerID is used in multiple nodes.
done

2022-05-04 18:13 UTC, Xenwar commented on baremetal/metal3machine_manager.go
> +		// There are, at least, two nodes. Details are in err
done

2022-05-04 18:18 UTC, Xenwar commented
/test-v1b1-ubuntu-integration
/test-v1b1-centos-integration
/test-v1b1-ubuntu-e2e
/test-v1b1-upgrade-e2e

2022-05-05 05:15 UTC, Xenwar commented
/test-v1b1-centos-integration

2022-05-11 11:07 UTC, Xenwar commented
@maelk If you have a comment on this PR. 
My thinking when creating this PR is to avoid provider-ID duplication that is introduced any way after the provisioning of a node.  Currently, we are preventing duplicate usage during provisioning of a node.

This PR breaks the check into two. 
1. duding provisioning 
2. regularly at intervals 

I would like to know if there are use cases that fit my assumption that:
- an isolated node using `metal3://bmh-id1` joins back the cluster after a while and the `metal3://bmh-id1` is used on a new node. 

or if there is any other use case that requires such duplicate detection. 
Thanks.

2022-05-25 10:51 UTC, Xenwar commented
PR no longer needed as other PRs have handled parts of it.

2022-05-25 10:51 UTC, closed without merging