WIP: 🌱 Seperate k8s and clusterctl upgrade tests
metal3-io/cluster-api-provider-metal3 pull request #963
Opened 2023-05-04 13:10 UTC by Sunnatillo

Adds labels to kubernetes and clusterctl upgrade tests to seperate the test using GINKGO_FOCUS

2023-05-05 07:38 UTC, Sunnatillo commented
/retest

2023-05-05 10:20 UTC, Sunnatillo commented
/hold

2023-05-05 11:38 UTC, adilGhaffarDev commented
/lgtm

2023-05-05 13:29 UTC, Rozzii requested changes

2023-05-05 13:31 UTC, Rozzii commented on scripts/environment.sh
>  # Upgrade test environment vars and config
But I would like to know your opinion @tuminoid  about this also.

2023-05-11 07:23 UTC, Sunnatillo commented on scripts/environment.sh
>  # Upgrade test environment vars and config
Addressed your comments.

2023-05-12 08:15 UTC, Sunnatillo commented
/test-centos-e2e-integration-main
/test-ubuntu-integration-main

2023-05-12 17:03 UTC, mboukhalfa commented
/lgtm

2023-05-31 10:11 UTC, lentzi90 reviewed
/lgtm

2023-05-31 12:08 UTC, Sunnatillo commented
/test-centos-e2e-integration-main
/test-ubuntu-integration-main

2023-06-01 10:16 UTC, mboukhalfa commented
/approve

2023-06-01 11:02 UTC, Sunnatillo commented
/hold until jjb [PR](https://gerrit.nordix.org/c/infra/cicd/+/18002) gets merged

2023-06-07 09:08 UTC, Sunnatillo commented
/unhold

2023-06-07 09:38 UTC, Rozzii approved these changes

2023-06-07 09:39 UTC, merged

2023-07-04 08:34 UTC, Sunnatillo commented
/cherry-pick release-1.4

2023-07-11 22:50 UTC, Sunnatillo commented
/cherry-pick release-1.3